---
- hosts: "{{ target_hosts }}"
  become: yes  # Run tasks with sudo privileges

  vars:
    package_list:
      - neofetch
      - make
      - libgraphicsmagick++-dev
      - libwebp-dev
      - python3-pip
      # Add more packages as needed

    repo_urls:
      - https://github.com/hzeller/rpi-rgb-led-matrix.git
      - https://github.com/SamEureka/love-matrix.git
      # Add more repository URLs as needed

    led_viewer_dir: "rpi-rgb-led-matrix/utils"
    love_source: "love-matrix/love"
    love_destination: "/opt"

  tasks:
    - name: Gather facts
      setup:

    - name: Check if OS is Ubuntu 23.10
      fail:
        msg: "This playbook is intended for Ubuntu 23.10 only."
      when: "ansible_facts['distribution'] != 'Ubuntu' or ansible_facts['distribution_version'] != '23.10'"


    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ package_list }}"
        state: present
        update_cache: yes

    - name: Clone repositories
      git:
        repo: "{{ item }}"
        dest: "{{ item | regex_replace('^.*/(.*).git$', '\\1') }}"
      with_items: "{{ repo_urls }}"

      - name: Set fact for cloned repositories
      set_fact:
        cloned_repo_paths: "{{ cloned_repos.results | map(attribute='dest') | list }}"
      when: cloned_repos.results | map(attribute='failed') | max == false

    - name: Build led-image-viewer
      shell:
        cmd: "make led-image-viewer"
        chdir: "{{ led_viewer_dir }}"
      ignore_errors: yes

    - name: Move love directory
      command: "mv {{ love_source }} {{ love_destination }}"
      become: yes

    - name: Change permissions
      file:
        path: "{{ love_destination }}/love/love.sh"
        mode: +x

    - name: Change permissions
      file:
        path: "{{ love_destination }}/love/toggler.sh"
        mode: +x

    - name: Add cron entry for love.sh
      cron:
        name: "Run love.sh at reboot"
        job: "cd {{ love_destination }}/love && ./love.sh"
        state: present

    - name: Add cron entry for toggler.sh
      cron:
        name: "Run toggler.sh at reboot"
        job: "cd {{ love_destination }}/love && ./toggler.sh"
        state: present

    - name: Delete repository folders
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ cloned_repo_paths | default([]) }}"